version: "3.9"  # optional since v1.27.0
services:
  frontend:
    restart: always
    image: images-gallery-frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    restart: always
    image: images-gallery-api
    ports:
      - "5050:5050"
    volumes:
      - ./api:/app